#!/bin/sh

ECHO=/bin/echo
USAGEMSG='USAGE: maketgz <version>'

VERSION=""
while [ $# -gt 0 ]
do
	case "$1" in
		-*)   $ECHO -e "$USAGEMSG"; exit 0;;
		*)    VERSION=$1;;
	esac
	shift
done
if [ -z "$VERSION" ]
then
	$ECHO -e "$USAGEMSG" 1>&2
	exit 1
fi

NAME="beamer-hn-$VERSION"
ln -s . "$NAME"
tar cvzf "${NAME}.tar.gz" \
	--no-recursion --exclude="$NAME" --exclude="${NAME}.tar.gz" \
	--exclude="*.snm" --exclude="*.nav" --recursion "$NAME"/*
rm "$NAME"
